# Generated by Django 3.0.1 on 2019-12-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_post_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=4000),
        ),
    ]
